### ISSUE TITLE
Glad to see someone continue my tweak 🙆‍♂️

### ISSUE THREAD

**Issue by spermlord** [MattStar45/samsungpowerdown13#1]

**Comment by MattStar45** [comment]
I wasn't able to get it to work fully on iOS 13 unfortunately but thank you so much for this tweak

**Comment by spermlord** [comment]
Do u get it to work on notch-related phone?

**Comment by MattStar45** [comment]
> Do u get it to work on notch-related phone?

It does work on notch related phones, however the issue arises with exiting it. I wasn’t able to figure that out as I’m very much new to objective c and tweak development :/

**Comment by spermlord** [comment]
nice, can u describe the issue?

**Comment by MattStar45** [comment]
> nice, can u describe the issue? and the log

Long story short apple redid closing the powerdown view and trying anything to close it will cause freezing on springboard. I don’t have any logs of it.

**Comment by spermlord** [comment]
u can continue work on it cuz I dont have any macos device to get it to work on newer iOS version. let continue it and if u want help from me, just pm me or comment on this issue anytime u want

**Comment by MattStar45** [comment]
> u can continue work on it cuz I dont have any macos device to get it to work on newer iOS version. let continue it and if u want help from me, just pm me or comment on this issue anytime u want
> 
> and please change the tweak author to it's original (aka me)

Ok I got you
